### ISSUE TITLE
Evaluate template options

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/directory#11]
We need any user-facing pages to adhere to adhere to CU's brand and accessibility standards.  Laravel 5.6 or > includes Bootstrap 4.  Do we just build something on that or do we want to but and customize something?

- https://laravel.com/docs/5.6/blade
- https://themeforest.net/item/laravel-admin-template-cubic/22321104

**Comment by alexfinnarn** [comment]
Vue is also an option, see https://github.com/cretueusebiu/laravel-vue-spa. I think more Laravel apps will start using Vue + Nuxt is SSR is needed rather than Blade templates.

https://blog.pusher.com/why-vuejs-laravel/

With the fact that every app won't be built in Laravel, i.e. Express on Drupal/Backdrop isn't going away, an app already built in Vue, and the fact that reactive JS frameworks are where everyone is headed, I don't think Blade templates make sense.

**Comment by alexfinnarn** [comment]
Okay, that article puts the Vue syntax into a Blade template for some reason, but that still works as well as it would using PHPTemplate in Drupal.

**Comment by alexfinnarn** [comment]
As far as any embedded component-y app in an HTML page, the current competing options are React, Vue, and Web Components.
