### ISSUE TITLE
Define requirements for static version of org list in JSON

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/directory#22]
The is very array('cart', 'horse'), but we need to define what the JSON the directory will provide to start integrating that with Drupal (for branding) and Help Scout for reporting and then work back to building the application to generate the output and figuring out how to host the application and endpoint.

Until we have the directory running as an application, we'll have to manually maintain the JSON.  To avoid that becoming another Atlas where Postman is the UI, we're going to limit edits to once a month.

You can already see how the type of site and parent are being used in https://github.com/CuBoulder/express/blob/branding/themes/ucb/template.php

**Comment by alexfinnarn** [comment]
https://github.com/alexfinnarn/directory/blob/feature/1/api/config/foo_schema.yaml#L2 is an example schema for an organization. That pulls from https://schema.org/Organization which is a great resource to use since it is supported in rich text snippets, rdf data, and has been worked on by many people who define entities like organizations.

**Comment by alexfinnarn** [comment]
I created https://github.com/alexfinnarn/directory_parser that currently creates a tree structure in JSON grouped by the hierarchy of parents to children orgs. It takes a CSV file to convert to JSON. I will add a flat structure of JSON with an entry per organization using the same CSV.
